[workspace]
members = [
  "backend/api",
  "backend/common",
  "backend/periodic-tasks",
  "backend/storage",
]

resolver = "2"

[profile.release]
lto = true
debug = false
opt-level = 3
strip = true

[patch.crates-io]
bip_metainfo = { path = "api/vendored/bip_metainfo" }
