[package]
name = "arcadia-periodic-tasks"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "fs"] }
tokio-cron-scheduler = "0.15"
arcadia-storage = { path = "../storage"}
arcadia-common = { path = "../common"}
arcadia-shared = { path = "../../shared"}
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.9", features = [ "runtime-tokio", "postgres", "chrono", "macros" ] }
serde_json = "1"
