[package]
name = "arcadia-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres", "chrono", "bigdecimal", "ipnetwork" ] }
