[package]
name = "arcadia-common"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-web-lab = "0.24.1"
thiserror = "2.0.12"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2.4"
